### ISSUE TITLE
Footer not reaching the bottom of the page

### ISSUE THREAD

**Issue by typicalname0** [lighterlightbulb/Rboxlo#11]
at https://rb.ozzt.pw/my/dashboard when you log in, there is a big gap at the bottom. I don't know if that's intentional but it looks out of place in my opinion.

**Comment by lighterlightbulb** [comment]
Could you take a screenshot and specify what browser/operating system you are using?

**Comment by typicalname0** [comment]
https://cdn.discordapp.com/attachments/699454586548650084/700131057722195988/unknown.png
Windows 10 Home Edition
1080p
Firefox 75

**Comment by typicalname0** [comment]
https://cdn.discordapp.com/attachments/699454586548650084/700131663275098252/unknown.png
tested with Chrome Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by lighterlightbulb** [comment]
Thanks, I will look into this issue.
