### ISSUE TITLE
Make the Uptime and User Count live updating on the statistics page

### ISSUE THREAD

**Issue by pizzaboxer** [lighterlightbulb/Rboxlo#15]
yeah, why not?

i probs wouldve tried to add this in myself actually ~~but i dont really know how to set this up in xampp lol~~ ok i'm dumb i didn't even realize there was an nginx conf file

bonus tip: add `header('Content-Type: application/vnd.api+json');` to all the endpoint pages, to help comply with the [json:api spec](https://jsonapi.org/format/)

**Comment by lighterlightbulb** [comment]
Uptime I'm pretty sure I can do live, but I don't see the point in live user counts... I doubt there's every going to be a high influx of users at a time to warrant that.

+1 for the JSON endpoint thing. If I have read the JSON.API spec correctly, I am pretty sure that it is the client that needs to send requests with the `application/vnd.api+json` header, and the server that sends back the `application/json` header. Correct me if I am wrong.

**Comment by pizzaboxer** [comment]
the `application/vnd.api+json` is used on both the client and server.
and i guess the live user count thing was a futureproofing idea, just in the case that there happened to be a large influx or anything.

**Comment by lighterlightbulb** [comment]
If you take a look at the JavaScript code in the statistics page, you can see how I automatically update the CPU and RAM usage. This same technique can be applied to the uptime. See if you can do that?

**Comment by lighterlightbulb** [comment]
> Uptime I'm pretty sure I can do live, but I don't see the point in live user counts... I doubt there's ever going to be a high influx of users at a time to warrant that.
> 
> +1 for the JSON endpoint thing. If I have read the JSON.API spec correctly, I am pretty sure that it is the client that needs to send requests with the `application/vnd.api+json` header, and the server that sends back the `application/json` header. Correct me if I am wrong.

Adding on to this: The client-sided JavaScript API always expects application/json, yet still works fine with text/plain. Interesting...

**Comment by pizzaboxer** [comment]
> If you take a look at the JavaScript code in the statistics page, you can see how I automatically update the CPU and RAM usage. This same technique can be applied to the uptime. See if you can do that?

sure thing
only thing is that the uptime would have to be parsed from the UNIX timestamp that the PHP `time()` function provides

**Comment by lighterlightbulb** [comment]
get_timestamp() returns a string timestamp.

**Comment by lighterlightbulb** [comment]
It seems that live uptime was implemented in v1.0.1. Live user counts will not be implemented, as it would mean a database query every second, making DDoSing exceptionally simple by opening a tab containing the statistics page several times.
