### ISSUE TITLE
Client???

### ISSUE THREAD

**Issue by Malte0621** [lighterlightbulb/Rboxlo#23]
Is there **ANY** way i can get a patched 2017 client, or learn how to patch it.
My whole life. I been looking for something like this. But i don't know how to _patch clients_.

If you could patch one. I would almost do anything. **Pay** money, Give an account. Buy nitro (If you have discord). Almost anything :(
I just really want my one and only, **biggest dream**. To come true..

I cant find any tutorials or help, anywhere.. **So please....**

-Malte0621, @lighterlightbulb

**Comment by Toast653** [comment]
Go download a 2017 studio or use finobe 2016.

**Comment by Toast653** [comment]
2017M Studio:  
https://drive.google.com/drive/mobile/folders/1XZpSoJGEsxC2UkKiypm_hIpU2yV4au9q/1lu1Ex6Z6D0TWUmqikrwD6tSDwVPTRze3/18_DvGVz16PfnGpTBR9VyfuGQ7GlLMkG7/1n4A_T_UckYIc2ToYP2HUx78odzTKBz4u?sort=13&direction=a # #22

**Comment by Toast653** [comment]
Also this is not the correct place to request this. This are issues for rboxlo not a suggestions or begging forum.

**Comment by lighterlightbulb** [comment]
Lol buy me nitro lightbulblighter#9166

**Comment by Malte0621** [comment]
Malte0621#4433 :/
