### ISSUE TITLE
Sub Domains.

### ISSUE THREAD

**Issue by Epiculy** [lighterlightbulb/Rboxlo#25]
I don't want to make so many sub domains. is there a way for rboxlo not to use it? And im not self hosting, using a hosting company

**Comment by lighterlightbulb** [comment]
You can remove everything in `domains.conf` except your primary domain and Rboxlo will work fine without it. However, the subdomains only exist to serve Roblox client APIs. If you so wish to remove all the subdomains, keep in mind an extra set of patching for each client may be required.
