### ISSUE TITLE
Questions.

### ISSUE THREAD

**Issue by Epiculy** [lighterlightbulb/Rboxlo#31]
1. Can I host it on a hosting provider not selfhost?
2. does the finobe client work with rboxlo. yes/no
3. if it doens't where do i look for one?

Epic#0313

**Comment by nickkerr** [comment]
aren’t you banned from finob for cookie logging 20 people 🤨

**Comment by nickkerr** [comment]
Please stop making issues

**Comment by lighterlightbulb** [comment]
1. Yes.
2. Rboxlo does not officially support the Finobe client, and never will.
3. You are supposed to create and patch your own client, and not steal from others.

One question: do you even know what you are doing? Nobody in their right mind would think that stealing a client from another revival would somehow seamlessly integrate with a random framework they found on GitHub. I advise you to study more about making Roblox private servers before making another issue.
