### ISSUE TITLE
Is there a way to use this infinityfree or some other online website hoster?

### ISSUE THREAD

**Issue by ktrain10298765** [lighterlightbulb/Rboxlo#49]
This is extremely confusing to me.

**Comment by lighterlightbulb** [comment]
Hi ktrain10298765,

Have you read the [Rboxlo server installation guide?](https://github.com/lighterlightbulb/Rboxlo/blob/master/INSTALL.md) See if that answers any of your questions. If you cannot install Docker on your hosting service, then Rboxlo will not work. That being said, you _could_ Frankenstein the codebase the work stand-alone from Docker, but I do not recommend that.

**Comment by lighterlightbulb** [comment]
Closed due to inactivity.
