### ISSUE TITLE
Link Rboxlo account to Discord account

### ISSUE THREAD

**Issue by Multako** [lighterlightbulb/Rboxlo#5]
allow a feature on the site that basically connects your discord account with Rboxlo account.
Using the functionality of a bot or something else.

**Comment by ozzt** [comment]
This can be done using Discord's [OAuth2 API](https://discordapp.com/developers/docs/topics/oauth2).

**Comment by lighterlightbulb** [comment]
This will be added soon(tm)

**Comment by Multako** [comment]
swag

**Comment by lighterlightbulb** [comment]
I am closing this issue because it is not an immediate priority; however, this *will* be added, and I will reopen this issue when the time comes.
