### ISSUE TITLE
Not redirecting properly even if secure cookies disabled???

### ISSUE THREAD

**Issue by sparksammy** [lighterlightbulb/Rboxlo#60]
Firefox, Internet Explorer, as well as Chromium-Based browsers (I use Edge, but it shouldn't matter.) don't redirect properly, even with secure cookies disabled, even in an Incognito window and with the default domain with hosts (rboxlo.loc). It would be great if someone could help me. Many thanks!

**Comment by lighterlightbulb** [comment]
Have you rebuilt with secure cookies disabled?

**Comment by sparksammy** [comment]
Yep, still having trouble, sadly. I am using the master branch.

**Comment by sparksammy** [comment]
update: i gave up.
