### ISSUE TITLE
Problem in building the localhost

### ISSUE THREAD

**Issue by HuntaDevisgay** [lighterlightbulb/Rboxlo#61]
Sadly when I execute the command
' docker-compose up --build '

It just throws me this

File "site-packages\docker\credentials\store.py", line 93, in _execute
docker.credentials.errors.StoreError: Credentials store docker-credential-desktop exited with "error listing credentials - err: exit status 1, out: `Has not found item.`".

**Comment by lighterlightbulb** [comment]
That looks like a Docker related issue with your install on your computer. Have you tried reinstalling Docker?

**Comment by lighterlightbulb** [comment]
Closed due to inactivity.
