### ISSUE TITLE
Docker command error

### ISSUE THREAD

**Issue by ittehgeps** [lighterlightbulb/Rboxlo#62]
When trying to use the docker command after I did all the previous steps, I get an error.

Step 16/32 : COPY .git/refs/heads/master /var/www/Packaging/Hash
ERROR: Service 'website' failed to build : COPY failed: stat /var/lib/docker/tmp/docker-builder207906778/.git/refs/heads/master: no such file or directory

I don't know if it has to do with Rboxlo or docker but I need help.

**Comment by lighterlightbulb** [comment]
You did not clone the repository using Git. Instead of downloading the source tree zip file on GitHub, run this command:

`git clone https://github.com/lighterlightbulb/Rboxlo`
