### ISSUE TITLE
chown: /var/www/data: Permission denied

### ISSUE THREAD

**Issue by SealOfficialYT** [lighterlightbulb/Rboxlo#64]
after running the docker compose i currently get this error:

website     | chown: /var/www/data: Permission denied

i've been trying everything i can to try to fix this but atm no luck

**Comment by lighterlightbulb** [comment]
I'm not sure how you'd get that error unless you are setting up outside of Docker. Can you copy and paste the error message exactly as it was?

**Comment by SealOfficialYT** [comment]
I've decided to reinstall my vps to ubuntu instead of centos to see if thats easier to setup.

**Comment by SealOfficialYT** [comment]
Okay so i've  fixed that issue but now i'm getting messages in my browser saying i'm being redirected too many times.

This is the console log;
website       | 127.0.0.1 -  31/Dec/2020:10:49:24 +0000 "GET /login.php" 302
website       | 127.0.0.1 -  31/Dec/2020:10:49:24 +0000 "GET /login.php" 302
website       | 127.0.0.1 -  31/Dec/2020:10:49:24 +0000 "GET /login.php" 302
website       | 127.0.0.1 -  31/Dec/2020:10:49:24 +0000 "GET /login.php" 302
website       | 127.0.0.1 -  31/Dec/2020:10:49:24 +0000 "GET /login.php" 302
website       | 127.0.0.1 -  31/Dec/2020:10:49:24 +0000 "GET /login.php" 302
website       | 127.0.0.1 -  31/Dec/2020:10:49:24 +0000 "GET /login.php" 302

**Comment by lighterlightbulb** [comment]
I will attempt to fix this today.

**Comment by lighterlightbulb** [comment]
Cannot reproduce. Can you try starting fresh and see what happens? Follow each step in the installation guide to the letter, and _then_ try making any modifications.

**Comment by lighterlightbulb** [comment]
Closed due to inactivity. Could not reproduce.
