### ISSUE TITLE
website | entrypoint.sh

### ISSUE THREAD

**Issue by Malte0621** [lighterlightbulb/Rboxlo#65]
Hello, i just installed docker and setup the image, following all provided instructions. Everything works, expect the website where i get this error:
`: not found   | /usr/local/bin/entrypoint.sh: line 2:
: No such file or directory/www
: not found   | /usr/local/bin/entrypoint.sh: line 5:
: not found   | /usr/local/bin/entrypoint.sh: line 7: nginx
website       | /usr/local/bin/entrypoint.sh: line 39: syntax error: unexpected "fi" (expecting "then")
website exited with code 2`

_Any help or ideas would help.._
**Image:**
![image](https://user-images.githubusercontent.com/50240920/103640905-219fd400-4f51-11eb-86bb-7d301aead733.png)

[Edit]:  Im not very active on github and might take up to a day before responding. Ill try my best to be active the rest of today.

**Comment by lighterlightbulb** [comment]
Did you modify your `Dockerfile` or `Website/Entrypoint.sh`? Try following the install instructions again by cloning the repository and starting anew. Unless there is some modification you are trying to make for your system but are failing to do properly.

**Comment by lighterlightbulb** [comment]
Closed due to inactivity.
