### ISSUE TITLE
"/usr/local/bin/entrypoint.sh: line 40: syntax error: unexpected "done" (expecting "then")"

### ISSUE THREAD

**Issue by ObsidianPlague** [lighterlightbulb/Rboxlo#66]
I followed the guide, and as instructed, tried viewing it with Docker.
However, the problem is, when I try using the command it tells me to use, it ends up with this.
```
: not found   | /usr/local/bin/entrypoint.sh: line 2:
: No such file or directory/www
: not found   | /usr/local/bin/entrypoint.sh: line 5:
: not found   | /usr/local/bin/entrypoint.sh: line 7: nginx
website       | /usr/local/bin/entrypoint.sh: line 40: syntax error: unexpected "done" (expecting "then")
website exited with code 2
```
Any help to fix this issue would be much appreciated.

**Comment by lighterlightbulb** [comment]
It seems that this issue is occurring for multiple users now (#65.) I will try fixing this issue and #63 today.

**Comment by lighterlightbulb** [comment]
Okay, so as I was trying to fix, I followed the instructions [here](https://github.com/lighterlightbulb/Rboxlo/blob/master/INSTALL.md) and could not reproduce. As I have said in #65, did you modify any parts of the codebase (besides `.env` and `api-keys.json`) before running the Docker Compose command?

**Comment by ObsidianPlague** [comment]
> 
> 
> Okay, so as I was trying to fix, I followed the instructions [here](https://github.com/lighterlightbulb/Rboxlo/blob/master/INSTALL.md) and could not reproduce. As I have said in #65, did you modify any parts of the codebase (besides `.env` and `api-keys.json`) before running the Docker Compose command?

The only parts of the codebase that were modified is `.env` and `api-keys.json`.

**Comment by lighterlightbulb** [comment]
So I am not sure how you could receive this error... are you perhaps trying to run an older version of Rboxlo?

**Comment by ObsidianPlague** [comment]
> 
> 
> So I am not sure how you could receive this error... are you perhaps trying to run an older version of Rboxlo?

It's the most recent release, it can't be that I don't think.

**Comment by lighterlightbulb** [comment]
Did you try installing with a fresh clone of the repository?

**Comment by ObsidianPlague** [comment]
> 
> 
> Did you try installing with a fresh clone of the repository?

Yeah, still isn't working.

**Comment by lighterlightbulb** [comment]
This is an extremely odd issue. Can you send the full call-stack (e.g. from startup to container exit) or a screenshot of the command prompt? I can't imagine what could be causing this issue.

**Comment by lighterlightbulb** [comment]
Also, do you have WSL2 installed and enabled?

**Comment by lighterlightbulb** [comment]
Closed due to inactivity.

**Comment by ObsidianPlague** [comment]
apologize for my inactivity but after finally trying to set it up again a month later, with wsl2 and everything, the problem still keeps occurring.
